# Page settings

baseURL = ""
languageCode = 'en-us'
title = 'FrenchmomSecrets Receipes'
theme = 'lugo'
googleAnalytics = "UA-xxxxxxxx-y"

[params]
  author = "Alexey Mendieta"
  description = "website for receipes"
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
theme = 'lugo'
