baseURL = 'https://based.cooking/'
languageCode = 'en-us'
title = 'Based Cooking'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
